### ISSUE TITLE
Compatible to SPI1 defined pins

### ISSUE THREAD

**Issue by moononournation** [mikey60/BW16-RTL8720DN-Module-Arduino#1]
I found SPI.cpp defined SPI1 as:
```
SPIClass SPI1((void *)(&spi_obj1), 21, 20, 19, 18);
```
So I suggest variant.cpp should revise to:
```
    {PA_15,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ | PIO_PWM    , NOT_INITIAL}, //D18
    {PA_14,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ | PIO_PWM    , NOT_INITIAL}, //D19
    {PA_13,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ              , NOT_INITIAL}, //D20
    {PA_12,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ | PIO_PWM    , NOT_INITIAL}, //D21
    {PA_27,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ | PIO_PWM    , NOT_INITIAL}, //D22
    {PA_30,    NOT_INITIAL, PIO_GPIO | PIO_GPIO_IRQ              , NOT_INITIAL}, //D23
```

**Comment by mikey60** [comment]
@moononournation,
Thank you for your suggestion.  That change should simplify the sketches with SPI.  I will make the changes, test and update the repository in the next few days.

**Comment by mikey60** [comment]
Suggestion incorporated on March 3, 2021.

**Comment by moononournation** [comment]
I have drafted a pinout diagram, please fell free to use it if you like it: https://drive.google.com/drive/folders/1YQveoeO_b4K02olye9zCxWRceGggz9C2

**Comment by mikey60** [comment]
Thank you.  I will include the diagram, but I don't have access rights.  You can include the file here or I can request access rights to your file on Google Drive if you prefer.

**Comment by moononournation** [comment]
try this:
https://drive.google.com/drive/folders/1YQveoeO_b4K02olye9zCxWRceGggz9C2

**Comment by moononournation** [comment]
just enabled share:

https://drive.google.com/drive/folders/1YQveoeO_b4K02olye9zCxWRceGggz9C2

**Comment by moononournation** [comment]
Sorry of the wrong BOOT pin, I have corrected it to PA7 pin and rename it to BURN:
https://drive.google.com/drive/folders/1YQveoeO_b4K02olye9zCxWRceGggz9C2

And I have written an instructables on how to program it:
https://www.instructables.com/RTL8720DN/

**Comment by mikey60** [comment]
I have updated to your latest pinout diagrams and added the link to your instructables page.
