### ISSUE TITLE
Variant.h updates

### ISSUE THREAD

**Issue by FL0WL0W** [mikey60/BW16-RTL8720DN-Module-Arduino#2]
The Variant.h also needs to be updated to select pins PB1 and PB2 for UART3 so that the AT serial can be used

**Comment by mikey60** [comment]
@FLOWLOW, Thank you for pointing that out.  I do not use the AT serial, but I will make that change to variant.h file and include it in the repository.

**Comment by mikey60** [comment]
Added modified variant.h file.
